Erezs-MacBook-Pro-2.local: 2014-05-27 10:13:47,914 - ERROR     	[             api:389   ]	INTEGRATION TESTING: Core - Main (Test) v0.1	(PID 28572)	Error Message: Service Access Error: Failed Service Call ServiceCallError: WFS service call failed: status code = 500, message = Error: SyntaxError: invalid syntax (custom_analytics_daily_report.py, line 54)
Traceback (most recent call last):
  File "/Users/erezrubinstein/nri_code/python/core/service/framework/api.py", line 262, in service_response_wrapper
    result = service_call_function(*args, **kwargs)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/workflow_api.py", line 308, in api_task_new
    status = app.add_task(flow, process, stage, task_params, context, task_options, project_root=project_root)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 329, in add_task
    return self.add_tasks(flow, process, stage, [task], context, options, project_root)[0]
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 366, in add_tasks
    task_obj = task_class.dict_init(self.cfg, self.logger, project_root, task)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 144, in dict_init
    original_id=original_id)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 64, in standard_init
    task = cls.basic_init(time_creation=time_creation, meta=meta)
  File "/Users/erezrubinstein/nri_code/python/core/common/business_logic/data.py", line 36, in basic_init
    data = cls()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/white_space_grid_analytics_task.py", line 12, in __init__
    super(WhiteSpaceGridAnalyticsTask, self).__init__()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/auto_task.py", line 42, in __init__
    CeleryAppProvider.get_app(load_tasks=True)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/celery_app_provider.py", line 47, in get_app
    register_core_celery_tasks_once(load_tasks=load_tasks)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/core_tasks.py", line 53, in register_core_celery_tasks_once
    for module_name in task_module_names
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/custom_analytics/custom_analytics_daily_report.py", line 54
    "_hours_ago": self.input.get("_hours_ago", None)
               ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "/Users/erezrubinstein/nri_code/python/core/service/framework/api.py", line 262, in service_response_wrapper
    result = service_call_function(*args, **kwargs)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_main/main_api.py", line 588, in api_white_space_analytics
    response = app.run_white_space_analytics(request, context)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_main/implementation/service_endpoints/white_space_endpoints.py", line 56, in run_white_space_analytics
    task_rec, context, timeout=timeout)
  File "/Users/erezrubinstein/nri_code/python/common/service_access/wfs_access.py", line 357, in call_task_new
    timeout=10000)
  File "/Users/erezrubinstein/nri_code/python/common/service_access/service_access.py", line 207, in service_call_post
    return self.process_response_json(response, svc_name, key_name=key_name, json_decoder=json_decoder)
  File "/Users/erezrubinstein/nri_code/python/common/service_access/service_access.py", line 314, in process_response_json
    raise ServiceCallError(msg, status_code=response.status_code)
ServiceCallError: WFS service call failed: status code = 500, message = Error: SyntaxError: invalid syntax (custom_analytics_daily_report.py, line 54)
Traceback (most recent call last):
  File "/Users/erezrubinstein/nri_code/python/core/service/framework/api.py", line 262, in service_response_wrapper
    result = service_call_function(*args, **kwargs)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/workflow_api.py", line 308, in api_task_new
    status = app.add_task(flow, process, stage, task_params, context, task_options, project_root=project_root)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 329, in add_task
    return self.add_tasks(flow, process, stage, [task], context, options, project_root)[0]
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 366, in add_tasks
    task_obj = task_class.dict_init(self.cfg, self.logger, project_root, task)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 144, in dict_init
    original_id=original_id)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 64, in standard_init
    task = cls.basic_init(time_creation=time_creation, meta=meta)
  File "/Users/erezrubinstein/nri_code/python/core/common/business_logic/data.py", line 36, in basic_init
    data = cls()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/white_space_grid_analytics_task.py", line 12, in __init__
    super(WhiteSpaceGridAnalyticsTask, self).__init__()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/auto_task.py", line 42, in __init__
    CeleryAppProvider.get_app(load_tasks=True)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/celery_app_provider.py", line 47, in get_app
    register_core_celery_tasks_once(load_tasks=load_tasks)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/core_tasks.py", line 53, in register_core_celery_tasks_once
    for module_name in task_module_names
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/custom_analytics/custom_analytics_daily_report.py", line 54
    "_hours_ago": self.input.get("_hours_ago", None)
               ^
SyntaxError: invalid syntax


Erezs-MacBook-Pro-2.local: 2014-05-27 10:13:47,914 - ERROR     	[             api:389   ]	INTEGRATION TESTING: Core - Main (Test) v0.1	(PID 28572)	Error Message: Service Access Error: Failed Service Call ServiceCallError: WFS service call failed: status code = 500, message = Error: SyntaxError: invalid syntax (custom_analytics_daily_report.py, line 54)
Traceback (most recent call last):
  File "/Users/erezrubinstein/nri_code/python/core/service/framework/api.py", line 262, in service_response_wrapper
    result = service_call_function(*args, **kwargs)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/workflow_api.py", line 308, in api_task_new
    status = app.add_task(flow, process, stage, task_params, context, task_options, project_root=project_root)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 329, in add_task
    return self.add_tasks(flow, process, stage, [task], context, options, project_root)[0]
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 366, in add_tasks
    task_obj = task_class.dict_init(self.cfg, self.logger, project_root, task)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 144, in dict_init
    original_id=original_id)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 64, in standard_init
    task = cls.basic_init(time_creation=time_creation, meta=meta)
  File "/Users/erezrubinstein/nri_code/python/core/common/business_logic/data.py", line 36, in basic_init
    data = cls()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/white_space_grid_analytics_task.py", line 12, in __init__
    super(WhiteSpaceGridAnalyticsTask, self).__init__()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/auto_task.py", line 42, in __init__
    CeleryAppProvider.get_app(load_tasks=True)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/celery_app_provider.py", line 47, in get_app
    register_core_celery_tasks_once(load_tasks=load_tasks)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/core_tasks.py", line 53, in register_core_celery_tasks_once
    for module_name in task_module_names
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/custom_analytics/custom_analytics_daily_report.py", line 54
    "_hours_ago": self.input.get("_hours_ago", None)
               ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "/Users/erezrubinstein/nri_code/python/core/service/framework/api.py", line 262, in service_response_wrapper
    result = service_call_function(*args, **kwargs)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_main/main_api.py", line 588, in api_white_space_analytics
    response = app.run_white_space_analytics(request, context)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_main/implementation/service_endpoints/white_space_endpoints.py", line 56, in run_white_space_analytics
    task_rec, context, timeout=timeout)
  File "/Users/erezrubinstein/nri_code/python/common/service_access/wfs_access.py", line 357, in call_task_new
    timeout=10000)
  File "/Users/erezrubinstein/nri_code/python/common/service_access/service_access.py", line 207, in service_call_post
    return self.process_response_json(response, svc_name, key_name=key_name, json_decoder=json_decoder)
  File "/Users/erezrubinstein/nri_code/python/common/service_access/service_access.py", line 314, in process_response_json
    raise ServiceCallError(msg, status_code=response.status_code)
ServiceCallError: WFS service call failed: status code = 500, message = Error: SyntaxError: invalid syntax (custom_analytics_daily_report.py, line 54)
Traceback (most recent call last):
  File "/Users/erezrubinstein/nri_code/python/core/service/framework/api.py", line 262, in service_response_wrapper
    result = service_call_function(*args, **kwargs)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/workflow_api.py", line 308, in api_task_new
    status = app.add_task(flow, process, stage, task_params, context, task_options, project_root=project_root)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 329, in add_task
    return self.add_tasks(flow, process, stage, [task], context, options, project_root)[0]
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/workflow_service.py", line 366, in add_tasks
    task_obj = task_class.dict_init(self.cfg, self.logger, project_root, task)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 144, in dict_init
    original_id=original_id)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/task.py", line 64, in standard_init
    task = cls.basic_init(time_creation=time_creation, meta=meta)
  File "/Users/erezrubinstein/nri_code/python/core/common/business_logic/data.py", line 36, in basic_init
    data = cls()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/white_space_grid_analytics_task.py", line 12, in __init__
    super(WhiteSpaceGridAnalyticsTask, self).__init__()
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/auto_task.py", line 42, in __init__
    CeleryAppProvider.get_app(load_tasks=True)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/celery_app_provider.py", line 47, in get_app
    register_core_celery_tasks_once(load_tasks=load_tasks)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/celery/core_tasks.py", line 53, in register_core_celery_tasks_once
    for module_name in task_module_names
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/erezrubinstein/nri_code/python/core/service/svc_workflow/implementation/task/implementation/custom_analytics/custom_analytics_daily_report.py", line 54
    "_hours_ago": self.input.get("_hours_ago", None)
               ^
SyntaxError: invalid syntax


